# Generated by Django 3.2.25 on 2025-07-05 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img1', models.ImageField(upload_to='pics')),
                ('img2', models.ImageField(upload_to='pics')),
                ('number', models.IntegerField(default=2)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='yatra.city')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=10)),
                ('trip_same_id', models.IntegerField(default=1)),
                ('amount', models.CharField(max_length=8)),
                ('status', models.CharField(default='Failed', max_length=15)),
                ('payment_method', models.CharField(blank=True, max_length=15)),
                ('date_time', models.CharField(default='2025-07-05 07:53:47', max_length=19)),
            ],
        ),
        migrations.CreateModel(
            name='PassengerDetail',
            fields=[
                ('trip_id', models.AutoField(primary_key=True, serialize=False)),
                ('trip_same_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('trip_date', models.DateField()),
                ('payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('city', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetailedDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField(default=5)),
                ('price', models.IntegerField(default=20000)),
                ('rating', models.IntegerField(default=5)),
                ('img1', models.ImageField(upload_to='pics')),
                ('img2', models.ImageField(upload_to='pics')),
                ('desc', models.TextField()),
                ('day1', models.CharField(blank=True, max_length=200)),
                ('day2', models.CharField(blank=True, max_length=200)),
                ('day3', models.CharField(blank=True, max_length=200)),
                ('day4', models.CharField(blank=True, max_length=200)),
                ('day5', models.CharField(blank=True, max_length=200)),
                ('day6', models.CharField(blank=True, max_length=200)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='yatra.destination')),
            ],
        ),
    ]
