# Generated by Django 3.2.25 on 2025-07-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yatra', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='number',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_time',
            field=models.CharField(default='2025-07-05 07:56:56', max_length=19),
        ),
    ]
