# Generated by Django 3.2.25 on 2025-07-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yatra', '0003_auto_20250705_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date_time',
            field=models.CharField(default='2025-07-05 09:49:54', max_length=19),
        ),
    ]
