# Generated by Django 3.2.25 on 2025-07-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yatra', '0005_auto_20250705_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_time',
            field=models.CharField(default='2025-07-05 10:27:07', max_length=19),
        ),
    ]
