# Generated by Django 3.2.25 on 2025-07-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yatra', '0006_auto_20250705_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_time',
            field=models.CharField(default='2025-07-05 10:43:00', max_length=19),
        ),
    ]
