# Generated by Django 3.2.25 on 2025-07-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yatra', '0007_auto_20250705_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerdetail',
            name='num_passengers',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_time',
            field=models.CharField(default='2025-07-17 05:56:40', max_length=19),
        ),
    ]
