# Generated by Django 3.2.25 on 2025-07-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yatra', '0008_auto_20250717_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date_time',
            field=models.CharField(default='2025-07-17 06:34:40', max_length=19),
        ),
    ]
