# Generated by Django 3.2.25 on 2025-07-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yatra', '0009_alter_transaction_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerdetail',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='passengerdetail',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='passengerdetail',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='passengerdetail',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_time',
            field=models.CharField(default='2025-07-21 07:21:15', max_length=19),
        ),
    ]
