# Generated by Django 5.2.4 on 2025-07-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yatra', '0010_auto_20250721_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date_time',
            field=models.CharField(default='2025-07-22 07:33:55', max_length=19),
        ),
    ]
